---
# used script template at: https://serversforhackers.com/c/create-user-in-ansible
- name: add users for deployment of app
  hosts: local
  become: true
  
  tasks:
    - name: add deploy user
      user: 
        name: deploy
        password: '$6$G1j2vqOhRa$QTtCWujfFUcyALSTXB.Nr1cGs2MHaoAB3t9oXUNwrNXlXPfTm.4ZePucZ/utLizQ30.zSVqGV8TJ/un/hiCK91'
        groups:
          - sudo
        state: present
        shell: /bin/bash
        system: no
        create_home: yes
        home: /home/deploy

