---
- name: install nginx
  hosts: local
  become: true
  
  tasks:
    - name: install nginx using apt
      apt: 
        name: nginx
        state: present

    - name: Enable nginx access through the firewall
      ufw:
        name: Nginx HTTP
        rule: allow
        state: enabled

    # need to add key and reposityory before trying to install passenger  
    - name: add key for passenger
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 561F9B9CAC40B2F7
        state: present

    - name: add passenger repository
      apt_repository:
        repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main
        state: present

    - name: install passenger libraries for nginx
      apt: 
        name: ['nginx-extras', 'libnginx-mod-http-passenger']
        state: present
    # configure passenger
    
