- name: Install required software in host
  user: 
        name: deploy
        password: '$6$wbxiWLP7IpH$KaTzp05SmP/EG1Ce6hHJh7Y.fuX0fWSouX3o6LyrHksO4rHyT3ltRgiYF8TbgIrqPQS2UaIa3YsDl7t3bpJhf0'
        groups:
          - sudo
        state: present
        shell: /bin/bash
        system: no
        create_home: yes
        home: /home/deploy

