---
- hosts: deploying
  become: true
  roles:
    - basic  #create user and install package dependencies
    - ruby # install rbenv and ruby for the app
    - nginx # install and setup nginx and passenger for deploying app